# NumPy Exercise

In [2]:

import numpy as np
    

### 1. Array creation and basic operations

In [13]:

# (1) Create a 10x10 random array with values between 0 and 100 (int)
arr = np.random.randint(0,101,dtype=int,size=(10,10))
print(arr)
    

[[79 58 97 24 49 34 12 24 46 28]
 [47 56 17 82 17 61 20 39 24 55]
 [65 42 77  8 54 51 63 33 15 57]
 [89 32 59 53 11 92  8 56 41 31]
 [12 84 89 86  4 32 28 21 47 81]
 [45 58 68 85 52 90 30  8  3 71]
 [76 33 20 35 23 89 45 74 46 88]
 [73 28 34 43 97 97 90 81 73 75]
 [ 2  9  9 17 37 63 36 33 16 40]
 [80 36 94 79 13 23 49 14 62 46]]


In [14]:

# (2) Calculate the minimum, maximum, and mean of the array
min_value = arr.min()   # Minimum value
max_value = arr.max()    # Maximum value
mean_value = arr.mean()  # Mean value

print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)
    

Min: 2 Max: 97 Mean: 47.78


In [15]:

# (3) Compute the sum of the array along rows or columns
row_sum = arr.sum(axis=1)  # Sum along rows
col_sum = arr.sum(axis=0)  # Sum along columns

print("Row sum:", row_sum)
print("Column sum:", col_sum)
    

Row sum: [451 418 465 472 484 510 529 691 262 496]
Column sum: [568 436 564 512 357 632 381 383 373 572]


### 2. Array reshaping and merging

In [16]:

# (1) Reshape the array into a 5x20 array
reshaped_array = arr.reshape(5, 20)
print("Reshaped array:", reshaped_array)
    

Reshaped array: [[79 58 97 24 49 34 12 24 46 28 47 56 17 82 17 61 20 39 24 55]
 [65 42 77  8 54 51 63 33 15 57 89 32 59 53 11 92  8 56 41 31]
 [12 84 89 86  4 32 28 21 47 81 45 58 68 85 52 90 30  8  3 71]
 [76 33 20 35 23 89 45 74 46 88 73 28 34 43 97 97 90 81 73 75]
 [ 2  9  9 17 37 63 36 33 16 40 80 36 94 79 13 23 49 14 62 46]]


In [20]:

# (2) Create a 1x20 array using np.ones, and concatenate it to the reshaped array along the rows
new_array = np.ones((1, 20))
# print("New array:", new_array)
concatenated_array = np.concatenate((reshaped_array, new_array), axis=0)
print("Concatenated array:", concatenated_array)
    

New array: [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Concatenated array: [[79. 58. 97. 24. 49. 34. 12. 24. 46. 28. 47. 56. 17. 82. 17. 61. 20. 39.
  24. 55.]
 [65. 42. 77.  8. 54. 51. 63. 33. 15. 57. 89. 32. 59. 53. 11. 92.  8. 56.
  41. 31.]
 [12. 84. 89. 86.  4. 32. 28. 21. 47. 81. 45. 58. 68. 85. 52. 90. 30.  8.
   3. 71.]
 [76. 33. 20. 35. 23. 89. 45. 74. 46. 88. 73. 28. 34. 43. 97. 97. 90. 81.
  73. 75.]
 [ 2.  9.  9. 17. 37. 63. 36. 33. 16. 40. 80. 36. 94. 79. 13. 23. 49. 14.
  62. 46.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]]


### 3. Logical operations and filtering

In [21]:

# (1) Use boolean indexing to find all elements greater than 50, and set them to 50
arr = arr.copy()
arr[arr>50]=50
print("Array after setting elements > 50 to 50:", arr)
    

Array after setting elements > 50 to 50: [[50 50 50 24 49 34 12 24 46 28]
 [47 50 17 50 17 50 20 39 24 50]
 [50 42 50  8 50 50 50 33 15 50]
 [50 32 50 50 11 50  8 50 41 31]
 [12 50 50 50  4 32 28 21 47 50]
 [45 50 50 50 50 50 30  8  3 50]
 [50 33 20 35 23 50 45 50 46 50]
 [50 28 34 43 50 50 50 50 50 50]
 [ 2  9  9 17 37 50 36 33 16 40]
 [50 36 50 50 13 23 49 14 50 46]]


In [23]:

# (2) Find the positions of all even numbers in the array
temp=np.where(arr % 2 == 0)
even_positions = list(zip(temp[0],temp[1]))
print("Even number positions:", even_positions)
    

Even number positions: [(0, 0), (0, 1), (0, 2), (0, 3), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (1, 1), (1, 3), (1, 5), (1, 6), (1, 8), (1, 9), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 9), (3, 0), (3, 1), (3, 2), (3, 3), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 9), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 9), (6, 0), (6, 2), (6, 5), (6, 7), (6, 8), (6, 9), (7, 0), (7, 1), (7, 2), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (8, 0), (8, 5), (8, 6), (8, 8), (8, 9), (9, 0), (9, 1), (9, 2), (9, 3), (9, 7), (9, 8), (9, 9)]


### 4. Linear algebra operations

In [24]:

# (1) Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print("Identity matrix:", identity_matrix)
    

Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:

# (2) Create a 3x3 random matrix and compute its inverse
random_matrix = np.random.rand(3, 3)
inv_matrix = np.linalg.inv(random_matrix)   # Inverse of the matrix

print("Random matrix:", random_matrix)
print("Inverse matrix:", inv_matrix)
    

Random matrix: [[0.81267225 0.6117213  0.52652948]
 [0.08673711 0.19388684 0.87736609]
 [0.5606248  0.79028011 0.56405961]]
Inverse matrix: [[ 2.5980845  -0.31612258 -1.93350636]
 [-1.97057301 -0.72608349  2.96884546]
 [ 0.17862308  1.3314825  -0.46492942]]


In [28]:

# (3) Matrix multiplication
matrix_product = np.dot(random_matrix, inv_matrix)
print("Matrix product (should be close to identity matrix):", matrix_product)
    

Matrix product (should be close to identity matrix): [[ 1.00000000e+00  0.00000000e+00  8.32667268e-17]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [-8.32667268e-17  0.00000000e+00  1.00000000e+00]]
